node {  
    stage('Build') { 
        git 'https://github.com/ravibabukonda/maven-web-application.git' 
        sh 'ls -ll' 
        sh 'rm -rf *.zip.*'
    }
    stage('Build') { 
        echo "This step is to build the java app with maven"
        sh 'mvn clean test' 
        sh 'ls -ll'
        sh 'cat Jenkinsfile'
        sh 'wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.zip' 
        sh 'ls -ll'
        
    }
    stage('Deploy to') { 
        // 
    }
}
