pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
             git  "https://github.com/ravibabukonda/maven-web-application.git"
               
            }
        }
        stage('Test') { 
            steps {
                // 
            }
        }
        stage('Deploy') { 
            steps {
                // 
            }
        }
    }
}
